### ISSUE TITLE
[BUG] DB transactions failing when logged in as other users in local dev

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#3726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When ghosting as a different user when running the app with the dev spring profile, queries from the frontend intermittently fail with frontend throwing or alerting a JSON unexpected EOF error. The backend logs show a `DuplicateKeyException` when trying to insert into the spring_session table.

### Steps To Reproduce

In local environment with dev spring profile:
1. As default user, click around the app, doing things to trigger backend queries like viewing patient list, viewing result list, searching for patients, etc. Check the `spring_session` table and see that it's empty.
2. Ghost in as any user. Check that the access_token key has been set in local storage in your browser.
![Screen Shot 2022-05-05 at 10 34 23 AM](https://user-images.githubusercontent.com/6401323/166980403-fc4b3e6b-04b0-4df8-993f-9ee742e2365d.png)
3. Click around the app again. Do this repeatedly until you get either an error toast or the `Something went wrong :(` error page. What you get will depend on how the frontend handles query errors for whatever component is being rendered. Check the `spring_session` table. It should have many rows for the user you are ghosted in as.
4. Use your tool of choice to delete all rows from the `spring_session` table. You should be able to refresh your page and see results. Clicking around the app some more will inevitably trigger an error again as the table is populated again.

### Expected Behavior

Expect errors to not happen when using the app as intended.

### Additional context

Once the `access_token` key is set in browser local storage, db transactions will start inserting rows in the spring_session table. A workaround is to delete all rows from this table whenever you get an error and refreshing the page. Or just avoid ghosting in as other users as much as possible.

Backend stack trace:
```
2022-05-04 10:53:36.181  INFO 2011 --- [onPool-worker-3] [Query: ] g.k.servlet.HttpRequestInvokerImpl       : Bad request: path was not "/schema.json" or no query variable named "query" given

java.util.concurrent.CompletionException: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [INSERT INTO simple_report.spring_session(PRIMARY_ID, SESSION_ID, CREATION_TIME, LAST_ACCESS_TIME, MAX_INACTIVE_INTERVAL, EXPIRY_TIME, PRINCIPAL_NAME) VALUES (?, ?, ?, ?, ?, ?, ?)]; ERROR: duplicate key value violates unique constraint "pk__spring_session"
  Detail: Key (primary_id)=(5855e155-7548-4707-b306-09ace02254eb) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk__spring_session"
  Detail: Key (primary_id)=(5855e155-7548-4707-b306-09ace02254eb) already exists.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137) ~[na:na]
```

Somewhat related to #3134.

Potentially an issue with Spring Session, like https://github.com/spring-projects/spring-session/issues/1213 or something similar.

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by mehansen** [comment]
Tested this in my local and it no longer fails. Thanks for fixing!
