### ISSUE TITLE
Fix azure-storage-common upgrade

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#5192]
### Description

- related to #5078
- the upgrade failed due to our usage of deprecated fields
- getting this error when submitting a testevent
```java
throwIfFatal detected a jvm fatal exception, which is thrown and logged below:n
java.lang.NoSuchMethodError: 'com.azure.core.util.BinaryData com.azure.core.http.HttpRequest.getBodyAsBinaryData()'n
at com.azure.storage.common.policy.RequestRetryPolicy.attemptAsync(RequestRetryPolicy.java:104) ~[azure-storage-common-12.19.2.jar!/:12.19.2]n	
at com.azure.storage.common.policy.RequestRetryPolicy.process(RequestRetryPolicy.java:55) ~[azure-storage-common-12.19.2.jar!/:12.19.2]n	
at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:46)
```

### Proposed solution 

- remove usage of deprecated code and migrate to the newest version

**Comment by zdeveloper** [comment]
fixed
