### ISSUE TITLE
Investigate collection date time is less than result date time for CO

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#7087]
Previous effort:
https://github.com/CDCgov/prime-simplereport/pull/6961

**Comment by emyl3** [comment]
Currently waiting to hear back with accession ids to send to Victor at ReportStream from the user:
https://skylight-hq.slack.com/archives/C05M1B22AHY/p1702575020911999

**Comment by emyl3** [comment]
Got accession id from user and information from Victor from ReportStream
checked our logs and saw we were getting an [`InvalidAddressException` from the server] for the ordering provider which could explain why it defaulted to EST (https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-simple-report-prod%22%2C%22Name%22%3A%22prime-simple-report-prod-insights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F7d1e3999-6577-4cd5-b296-f518e5c8e677%252FresourceGroups%252Fprime-simple-report-prod%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fprime-simple-report-prod-insights%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%22b04c71f3-8d50-11ee-8bc4-6045bdd71865%22%2C%22timestamp%22%3A%222023-11-27T18%3A13%3A19.890Z%22%2C%22cacheId%22%3A%226ea36756-f876-4b84-8ae1-2f00eeea2315%22%2C%22eventTable%22%3A%22dependencies%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A172800000%2C%22endTime%22%3A%222023-11-28T19%3A30%3A06.489Z%22%7D%7D):

```
gov.cdc.usds.simplereport.service.errors.InvalidAddressException: The server is unable to verify the address you entered.
	at gov.cdc.usds.simplereport.service.AddressValidationService.getTimezoneInfoByLookup(AddressValidationService.java:106)
	at gov.cdc.usds.simplereport.service.AddressValidationService.getZoneIdByLookup(AddressValidationService.java:139)
	at gov.cdc.usds.simplereport.service.AddressValidationService.getZoneIdByAddress(AddressValidationService.java:133)
	at gov.cdc.usds.simplereport.service.ResultsUploaderCachingService.getZoneIdByAddress(ResultsUploaderCachingService.java:204)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
	at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:54)
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:366)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:420)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703)
	at gov.cdc.usds.simplereport.service.ResultsUploaderCachingService$$SpringCGLIB$$0.getZoneIdByAddress(<generated>)
	at gov.cdc.usds.simplereport.utils.DateTimeUtils.convertToZonedDateTime(DateTimeUtils.java:80)
	at gov.cdc.usds.simplereport.service.TestResultUploadService.transformCsvRow(TestResultUploadService.java:260)
	at gov.cdc.usds.simplereport.service.TestResultUploadService.transformCsvContent(TestResultUploadService.java:196)
	at gov.cdc.usds.simplereport.service.TestResultUploadService.lambda$submitResultsToCovidPipeline$4(TestResultUploadService.java:410)
	at gov.cdc.usds.simplereport.utils.AsyncLoggingUtils.lambda$withMDC$0(AsyncLoggingUtils.java:15)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

```

**Comment by emyl3** [comment]
I was looking into the stack trace more closely and realized that this was happening in the `TestResultUploadService` that submits the results to the COVID PIPELINE and not the FHIR one. 🤦 

I'll open a PR to update the `[TestResultUploadService](https://github.com/CDCgov/prime-simplereport/blob/3df31571b74c70b254789eb846f098767d7ebd1a/backend/src/main/java/gov/cdc/usds/simplereport/service/TestResultUploadService.java#L260)` to have the same changes as #6961
